from src.models import db, Pokemon, Type, PokemonType
from src.app import app

# Datos de tipos en español
TYPES = [
    {"name": "Agua", "image": "static/img/types/agua.png"},
    {"name": "Bicho", "image": "static/img/types/bicho.png"},
    {"name": "Dragon", "image": "static/img/types/dragon.png"},
    {"name": "Electrico", "image": "static/img/types/electrico.png"},
    {"name": "Fantasma", "image": "static/img/types/fantasma.png"},
    {"name": "Hielo", "image": "static/img/types/.png"},
    {"name": "Lucha", "image": "static/img/types/.png"},
    {"name": "Normal", "image": "static/img/types/.png"},
    {"name": "Planta", "image": "static/img/types/.png"},
    {"name": "Psiquico", "image": "static/img/types/.png"},
    {"name": "Roca", "image": "static/img/types/.png"},
    {"name": "Tierra", "image": "static/img/types/.png"},
    {"name": "Veneno", "image": "static/img/types/.png"},
    {"name": "Volador", "image": "static/img/types/.png"},
    {"name": "Fuego", "image": "static/img/types/fuego.png"},
    ]

POKEMON = [
    {"name": "Bulbasaur", "image": "static/img/pokemon/bulbasaur.png", "types": ["Planta", "Veneno"]},
    {"name": "Ivysaur", "image": "static/img/pokemon/ivysaur.png", "types": ["Planta", "Veneno"]},
    {"name": "Venusaur", "image": "static/img/pokemon/venusaur.png", "types": ["Planta", "Veneno"]},
    {"name": "Charmander", "image": "static/img/pokemon/charmander.png", "types": ["Fuego"]},
    {"name": "Charmeleon", "image": "static/img/pokemon/charmeleon.png", "types": ["Fuego"]},
    {"name": "Charizard", "image": "static/img/pokemon/charizard.png", "types": ["Fuego", "Volador"]},
    {"name": "Squirtle", "image": "static/img/pokemon/squirtle.png", "types": ["Agua"]},
    {"name": "Wartortle", "image": "static/img/pokemon/wartortle.png", "types": ["Agua"]},
    {"name": "Blastoise", "image": "static/img/pokemon/blastoise.png", "types": ["Agua"]},
    {"name": "Caterpie", "image": "static/img/pokemon/caterpie.png", "types": ["Bicho"]},
    {"name": "Metapod", "image": "static/img/pokemon/metapod.png", "types": ["Bicho"]},
    {"name": "Butterfree", "image": "static/img/pokemon/butterfree.png", "types": ["Bicho", "Volador"]},
    {"name": "Weedle", "image": "static/img/pokemon/weedle.png", "types": ["Bicho", "Veneno"]},
    {"name": "Kakuna", "image": "static/img/pokemon/kakuna.png", "types": ["Bicho", "Veneno"]},
    {"name": "Beedrill", "image": "static/img/pokemon/beedrill.png", "types": ["Bicho", "Veneno"]},
    {"name": "Pidgey", "image": "static/img/pokemon/pidgey.png", "types": ["Normal", "Volador"]},
    {"name": "Pidgeotto", "image": "static/img/pokemon/pidgeotto.png", "types": ["Normal", "Volador"]},
    {"name": "Pidgeot", "image": "static/img/pokemon/pidgeot.png", "types": ["Normal", "Volador"]},
    {"name": "Rattata", "image": "static/img/pokemon/rattata.png", "types": ["Normal"]},
    {"name": "Raticate", "image": "static/img/pokemon/raticate.png", "types": ["Normal"]},
    {"name": "Spearow", "image": "static/img/pokemon/spearow.png", "types": ["Normal", "Volador"]},
    {"name": "Fearow", "image": "static/img/pokemon/fearow.png", "types": ["Normal", "Volador"]},
    {"name": "Ekans", "image": "static/img/pokemon/ekans.png", "types": ["Veneno"]},
    {"name": "Arbok", "image": "static/img/pokemon/arbok.png", "types": ["Veneno"]},
    {"name": "Pikachu", "image": "static/img/pokemon/pikachu.png", "types": ["Eléctrico"]},
    {"name": "Raichu", "image": "static/img/pokemon/raichu.png", "types": ["Eléctrico"]},
    {"name": "Sandshrew", "image": "static/img/pokemon/sandshrew.png", "types": ["Tierra"]},
    {"name": "Sandslash", "image": "static/img/pokemon/sandslash.png", "types": ["Tierra"]},
    {"name": "Nidoran♀", "image": "static/img/pokemon/nidoran_f.png", "types": ["Veneno"]},
    {"name": "Nidorina", "image": "static/img/pokemon/nidorina.png", "types": ["Veneno"]},
    {"name": "Nidoqueen", "image": "static/img/pokemon/nidoqueen.png", "types": ["Veneno", "Tierra"]},
    {"name": "Nidoran♂", "image": "static/img/pokemon/nidoran_m.png", "types": ["Veneno"]},
    {"name": "Nidorino", "image": "static/img/pokemon/nidorino.png", "types": ["Veneno"]},
    {"name": "Nidoking", "image": "static/img/pokemon/nidoking.png", "types": ["Veneno", "Tierra"]},
    {"name": "Clefairy", "image": "static/img/pokemon/clefairy.png", "types": ["Hada"]},
    {"name": "Clefable", "image": "static/img/pokemon/clefable.png", "types": ["Hada"]},
    {"name": "Vulpix", "image": "static/img/pokemon/vulpix.png", "types": ["Fuego"]},
    {"name": "Ninetales", "image": "static/img/pokemon/ninetales.png", "types": ["Fuego"]},
    {"name": "Jigglypuff", "image": "static/img/pokemon/jigglypuff.png", "types": ["Normal", "Hada"]},
    {"name": "Wigglytuff", "image": "static/img/pokemon/wigglytuff.png", "types": ["Normal", "Hada"]},
    {"name": "Zubat", "image": "static/img/pokemon/zubat.png", "types": ["Veneno", "Volador"]},
    {"name": "Golbat", "image": "static/img/pokemon/golbat.png", "types": ["Veneno", "Volador"]},
    {"name": "Oddish", "image": "static/img/pokemon/oddish.png", "types": ["Planta", "Veneno"]},
    {"name": "Gloom", "image": "static/img/pokemon/gloom.png", "types": ["Planta", "Veneno"]},
    {"name": "Vileplume", "image": "static/img/pokemon/vileplume.png", "types": ["Planta", "Veneno"]},
    {"name": "Paras", "image": "static/img/pokemon/paras.png", "types": ["Bicho", "Planta"]},
    {"name": "Parasect", "image": "static/img/pokemon/parasect.png", "types": ["Bicho", "Planta"]},
    {"name": "Venonat", "image": "static/img/pokemon/venonat.png", "types": ["Bicho", "Veneno"]},
    {"name": "Venomoth", "image": "static/img/pokemon/venomoth.png", "types": ["Bicho", "Veneno"]},
    {"name": "Diglett", "image": "static/img/pokemon/diglett.png", "types": ["Tierra"]},
    {"name": "Dugtrio", "image": "static/img/pokemon/dugtrio.png", "types": ["Tierra"]},
    {"name": "Meowth", "image": "static/img/pokemon/meowth.png", "types": ["Normal"]},
    {"name": "Persian", "image": "static/img/pokemon/persian.png", "types": ["Normal"]},
    {"name": "Psyduck", "image": "static/img/pokemon/psyduck.png", "types": ["Agua"]},
    {"name": "Golduck", "image": "static/img/pokemon/golduck.png", "types": ["Agua"]},
    {"name": "Mankey", "image": "static/img/pokemon/mankey.png", "types": ["Lucha"]},
    {"name": "Primeape", "image": "static/img/pokemon/primeape.png", "types": ["Lucha"]},
    {"name": "Growlithe", "image": "static/img/pokemon/growlithe.png", "types": ["Fuego"]},
    {"name": "Arcanine", "image": "static/img/pokemon/arcanine.png", "types": ["Fuego"]},
    {"name": "Poliwag", "image": "static/img/pokemon/poliwag.png", "types": ["Agua"]},
    {"name": "Poliwhirl", "image": "static/img/pokemon/poliwhirl.png", "types": ["Agua"]},
    {"name": "Poliwrath", "image": "static/img/pokemon/poliwrath.png", "types": ["Agua", "Lucha"]},
    {"name": "Abra", "image": "static/img/pokemon/abra.png", "types": ["Psíquico"]},
    {"name": "Kadabra", "image": "static/img/pokemon/kadabra.png", "types": ["Psíquico"]},
    {"name": "Alakazam", "image": "static/img/pokemon/alakazam.png", "types": ["Psíquico"]},
    {"name": "Machop", "image": "static/img/pokemon/machop.png", "types": ["Lucha"]},
    {"name": "Machoke", "image": "static/img/pokemon/machoke.png", "types": ["Lucha"]},
    {"name": "Machamp", "image": "static/img/pokemon/machamp.png", "types": ["Lucha"]},
    {"name": "Bellsprout", "image": "static/img/pokemon/bellsprout.png", "types": ["Planta", "Veneno"]},
    {"name": "Weepinbell", "image": "static/img/pokemon/weepinbell.png", "types": ["Planta", "Veneno"]},
    {"name": "Victreebel", "image": "static/img/pokemon/victreebel.png", "types": ["Planta", "Veneno"]},
    {"name": "Tentacool", "image": "static/img/pokemon/tentacool.png", "types": ["Agua", "Veneno"]},
    {"name": "Tentacruel", "image": "static/img/pokemon/tentacruel.png", "types": ["Agua", "Veneno"]},
    {"name": "Geodude", "image": "static/img/pokemon/geodude.png", "types": ["Roca", "Tierra"]},
    {"name": "Graveler", "image": "static/img/pokemon/graveler.png", "types": ["Roca", "Tierra"]},
    {"name": "Golem", "image": "static/img/pokemon/golem.png", "types": ["Roca", "Tierra"]},
    {"name": "Ponyta", "image": "static/img/pokemon/ponyta.png", "types": ["Fuego"]},
    {"name": "Rapidash", "image": "static/img/pokemon/rapidash.png", "types": ["Fuego"]},
    {"name": "Slowpoke", "image": "static/img/pokemon/slowpoke.png", "types": ["Agua", "Psíquico"]},
    {"name": "Slowbro", "image": "static/img/pokemon/slowbro.png", "types": ["Agua", "Psíquico"]},
    {"name": "Magnemite", "image": "static/img/pokemon/magnemite.png", "types": ["Eléctrico", "Acero"]},
    {"name": "Magneton", "image": "static/img/pokemon/magneton.png", "types": ["Eléctrico", "Acero"]},
    {"name": "Farfetch’d", "image": "static/img/pokemon/farfetchd.png", "types": ["Normal", "Volador"]},
    {"name": "Doduo", "image": "static/img/pokemon/doduo.png", "types": ["Normal", "Volador"]},
    {"name": "Dodrio", "image": "static/img/pokemon/dodrio.png", "types": ["Normal", "Volador"]},
    {"name": "Seel", "image": "static/img/pokemon/seel.png", "types": ["Agua"]},
    {"name": "Dewgong", "image": "static/img/pokemon/dewgong.png", "types": ["Agua", "Hielo"]},
    {"name": "Grimer", "image": "static/img/pokemon/grimer.png", "types": ["Veneno"]},
    {"name": "Muk", "image": "static/img/pokemon/muk.png", "types": ["Veneno"]},
    {"name": "Shellder", "image": "static/img/pokemon/shellder.png", "types": ["Agua"]},
    {"name": "Cloyster", "image": "static/img/pokemon/cloyster.png", "types": ["Agua", "Hielo"]},
    {"name": "Gastly", "image": "static/img/pokemon/gastly.png", "types": ["Fantasma", "Veneno"]},
    {"name": "Haunter", "image": "static/img/pokemon/haunter.png", "types": ["Fantasma", "Veneno"]},
    {"name": "Gengar", "image": "static/img/pokemon/gengar.png", "types": ["Fantasma", "Veneno"]},
    {"name": "Onix", "image": "static/img/pokemon/onix.png", "types": ["Roca", "Tierra"]},
    {"name": "Drowzee", "image": "static/img/pokemon/drowzee.png", "types": ["Psíquico"]},
    {"name": "Hypno", "image": "static/img/pokemon/hypno.png", "types": ["Psíquico"]},
    {"name": "Krabby", "image": "static/img/pokemon/krabby.png", "types": ["Agua"]},
    {"name": "Kingler", "image": "static/img/pokemon/kingler.png", "types": ["Agua"]},
    {"name": "Voltorb", "image": "static/img/pokemon/voltorb.png", "types": ["Eléctrico"]},
    {"name": "Electrode", "image": "static/img/pokemon/electrode.png", "types": ["Eléctrico"]},
    {"name": "Exeggcute", "image": "static/img/pokemon/exeggcute.png", "types": ["Planta", "Psíquico"]},
    {"name": "Exeggutor", "image": "static/img/pokemon/exeggutor.png", "types": ["Planta", "Psíquico"]},
    {"name": "Cubone", "image": "static/img/pokemon/cubone.png", "types": ["Tierra"]},
    {"name": "Marowak", "image": "static/img/pokemon/marowak.png", "types": ["Tierra"]},
    {"name": "Hitmonlee", "image": "static/img/pokemon/hitmonlee.png", "types": ["Lucha"]},
    {"name": "Hitmonchan", "image": "static/img/pokemon/hitmonchan.png", "types": ["Lucha"]},
    {"name": "Lickitung", "image": "static/img/pokemon/lickitung.png", "types": ["Normal"]},
    {"name": "Koffing", "image": "static/img/pokemon/koffing.png", "types": ["Veneno"]},
    {"name": "Weezing", "image": "static/img/pokemon/weezing.png", "types": ["Veneno"]},
    {"name": "Rhyhorn", "image": "static/img/pokemon/rhyhorn.png", "types": ["Tierra", "Roca"]},
    {"name": "Rhydon", "image": "static/img/pokemon/rhydon.png", "types": ["Tierra", "Roca"]},
    {"name": "Chansey", "image": "static/img/pokemon/chansey.png", "types": ["Normal"]},
    {"name": "Tangela", "image": "static/img/pokemon/tangela.png", "types": ["Planta"]},
    {"name": "Kangaskhan", "image": "static/img/pokemon/kangaskhan.png", "types": ["Normal"]},
    {"name": "Horsea", "image": "static/img/pokemon/horsea.png", "types": ["Agua"]},
    {"name": "Seadra", "image": "static/img/pokemon/seadra.png", "types": ["Agua"]},
    {"name": "Goldeen", "image": "static/img/pokemon/goldeen.png", "types": ["Agua"]},
    {"name": "Seaking", "image": "static/img/pokemon/seaking.png", "types": ["Agua"]},
    {"name": "Staryu", "image": "static/img/pokemon/staryu.png", "types": ["Agua"]},
    {"name": "Starmie", "image": "static/img/pokemon/starmie.png", "types": ["Agua", "Psíquico"]},
    {"name": "Mr. Mime", "image": "static/img/pokemon/mr_mime.png", "types": ["Psíquico", "Hada"]},
    {"name": "Scyther", "image": "static/img/pokemon/scyther.png", "types": ["Bicho", "Volador"]},
    {"name": "Jynx", "image": "static/img/pokemon/jynx.png", "types": ["Hielo", "Psíquico"]},
    {"name": "Electabuzz", "image": "static/img/pokemon/electabuzz.png", "types": ["Eléctrico"]},
    {"name": "Magmar", "image": "static/img/pokemon/magmar.png", "types": ["Fuego"]},
    {"name": "Pinsir", "image": "static/img/pokemon/pinsir.png", "types": ["Bicho"]},
    {"name": "Tauros", "image": "static/img/pokemon/tauros.png", "types": ["Normal"]},
    {"name": "Magikarp", "image": "static/img/pokemon/magikarp.png", "types": ["Agua"]},
    {"name": "Gyarados", "image": "static/img/pokemon/gyarados.png", "types": ["Agua", "Volador"]},
    {"name": "Lapras", "image": "static/img/pokemon/lapras.png", "types": ["Agua", "Hielo"]},
    {"name": "Ditto", "image": "static/img/pokemon/ditto.png", "types": ["Normal"]},
    {"name": "Eevee", "image": "static/img/pokemon/eevee.png", "types": ["Normal"]},
    {"name": "Vaporeon", "image": "static/img/pokemon/vaporeon.png", "types": ["Agua"]},
    {"name": "Jolteon", "image": "static/img/pokemon/jolteon.png", "types": ["Eléctrico"]},
    {"name": "Flareon", "image": "static/img/pokemon/flareon.png", "types": ["Fuego"]},
    {"name": "Porygon", "image": "static/img/pokemon/porygon.png", "types": ["Normal"]},
    {"name": "Omanyte", "image": "static/img/pokemon/omanyte.png", "types": ["Roca", "Agua"]},
    {"name": "Omastar", "image": "static/img/pokemon/omastar.png", "types": ["Roca", "Agua"]},
    {"name": "Kabuto", "image": "static/img/pokemon/kabuto.png", "types": ["Roca", "Agua"]},
    {"name": "Kabutops", "image": "static/img/pokemon/kabutops.png", "types": ["Roca", "Agua"]},
    {"name": "Aerodactyl", "image": "static/img/pokemon/aerodactyl.png", "types": ["Roca", "Volador"]},
    {"name": "Snorlax", "image": "static/img/pokemon/snorlax.png", "types": ["Normal"]},
    {"name": "Articuno", "image": "static/img/pokemon/articuno.png", "types": ["Hielo", "Volador"]},
    {"name": "Zapdos", "image": "static/img/pokemon/zapdos.png", "types": ["Eléctrico", "Volador"]},
    {"name": "Moltres", "image": "static/img/pokemon/moltres.png", "types": ["Fuego", "Volador"]},
    {"name": "Dratini", "image": "static/img/pokemon/dratini.png", "types": ["Dragón"]},
    {"name": "Dragonair", "image": "static/img/pokemon/dragonair.png", "types": ["Dragón"]},
    {"name": "Dragonite", "image": "static/img/pokemon/dragonite.png", "types": ["Dragón", "Volador"]},
    {"name": "Mewtwo", "image": "static/img/pokemon/mewtwo.png", "types": ["Psíquico"]},
    {"name": "Mew", "image": "static/img/pokemon/mew.png", "types": ["Psíquico"]},
    ]


def populate_data():
    with app.app_context():
        # Añadir tipos
        for t in TYPES:
            type_entry = Type(name=t["name"], image=t["image"])
            db.session.add(type_entry)
        
        db.session.commit()

        # Añadir Pokémon
        for p in POKEMON:
            pokemon_entry = Pokemon(name=p["name"], image=p["image"])
            for t_name in p["types"]:
                type_entry = Type.query.filter_by(name=t_name).first()
                pokemon_entry.types.append(PokemonType(type=type_entry))
            db.session.add(pokemon_entry)

        db.session.commit()
        print("Base de datos poblada con éxito")

if __name__ == '__main__':
    populate_data()
